PRAGMA foreign_keys = false;
BEGIN;
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('server_addr', '0.0.0.0', '', '连接服务端的地址', '', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('server_port', '7000', '', '连接服务端的端口', '', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('connect_server_local_ip', '无', '', '连接服务端时所绑定的本地 IP', '', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('dial_server_timeout', '10', '', '连接服务端的超时时间', '', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('dial_server_keepalive', '7200', '', '和服务端底层 TCP 连接的 keepalive 间隔时间，单位秒', '', '负数不启用', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('http_proxy', '无', '', '连接服务端使用的代理地址', '', '格式为 {protocol}://user:passwd@192.168.1.128:8080 protocol 目前支持 http、socks5、ntlm', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('log_file', '', '', '日志文件地址', '', '如果设置为 console，会将日志打印在标准输出中', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('log_level', 'info', '', '日志等级', 'trace,debug,info,warn,error', '格式为 {protocol}://user:passwd@192.168.1.128:8080 protocol 目前支持 http、socks5、ntlm', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('log_max_days', '3', '', '日志文件保留天数', '', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('disable_log_color', 'false', '', '禁用标准输出中的日志颜色', 'false,true', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('pool_count', '0', '', '连接池大小', 'false,true', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('user', '无', '', '用户名', '', '设置此参数后，代理名称会被修改为 {user}.{proxyName}，避免代理名称和其他用户冲突', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('dns_server', '无', '', '使用 DNS 服务器地址', '', '默认使用系统配置的 DNS 服务器，指定此参数可以强制替换为自定义的 DNS 服务器地址', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('login_fail_exit', 'true', '', '第一次登陆失败后是否退出', '', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('protocol', 'tcp', '', '连接服务端的通信协议', 'tcp,kcp,websocket', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('tls_enable', 'false', '', '启用 TLS 协议加密连接', 'true,false', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('tls_cert_file', '无', '', 'TLS 客户端证书文件路径', '', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('tls_key_file', '无', '', 'TLS 客户端密钥文件路径', '', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('tls_trusted_ca_file', '无', '', 'TLS CA 证书路径', '', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('tls_server_name', '无', '', 'TLS Server 名称', '', '为空则使用 server_addr', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('disable_custom_tls_first_byte', 'false', '', 'TLS 不发送 0x17', 'true,false', '当为 true 时，不能端口复用', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('tcp_mux_keepalive_interval', '30', '', '向服务端发送心跳包的间隔时间', '', '建议启用 tcp_mux_keepalive_interval，将此值设置为 -1', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('heartbeat_timeout', '90', '', '和服务端心跳的超时时间', '', '', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('udp_packet_size', '1500', '', '代理 UDP 服务时支持的最大包长度', '', '服务端和客户端的值需要一致', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('start', '1500', '', '指定启用部分代理', '', '当配置了较多代理，但是只希望启用其中部分时可以通过此参数指定，默认为全部启用', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('meta_xxx', '无', '', '附加元数据', '', '会传递给服务端插件，提供附加能力', 'common');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('authentication_method', 'token', '', '鉴权方式', '', '需要和服务端一致', 'auth');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('authenticate_heartbeats', 'false', '', '开启心跳消息鉴权', 'true,false', '需要和服务端一致', 'auth');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('authenticate_new_work_conns', 'false', '', '开启建立工作连接的鉴权', 'true,false', '需要和服务端一致', 'auth');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('token', '无', '', '鉴权使用的 token 值', '', '需要和服务端设置一样的值才能鉴权通过', 'auth');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('oidc_client_id', '无', '', 'oidc_client_id', '', '', 'auth');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('oidc_client_secret', '无', '', 'oidc_client_secret', '', '', 'auth');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('oidc_audience', '无', '', 'oidc_audience', '', '', 'auth');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('oidc_token_endpoint_url', '无', '', 'oidc_token_endpoint_url', '', '', 'auth');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('oidc_additional_xxx', '无', '', 'OIDC 附加参数', '', 'map 结构，key 需要以 oidc_additional_ 开头', 'auth');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('admin_addr', '0.0.0.0', '', '启用 AdminUI 监听的本地地址', '', '', 'ui');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('admin_port', '0', '', '启用 AdminUI 监听的本地端口', '', '', 'ui');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('admin_user', '无', '', 'HTTP BasicAuth 用户名', '', '', 'ui');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('admin_pwd', '无', '', 'HTTP BasicAuth 密码', '', '', 'ui');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('asserts_dir', '无', '', '静态资源目录', '', 'AdminUI 使用的资源默认打包在二进制文件中，通过指定此参数使用自定义的静态资源', 'ui');
INSERT INTO "client_setting" ("key", "default_value", "value", "desc", "options", "remark", "set_type") VALUES ('pprof_enable', 'false', '', '启动 Go HTTP pprof', 'true,false', '用于应用调试', 'ui');
COMMIT;

PRAGMA foreign_keys = true;
